#!/bin/bash

export DEBIAN_FRONTEND=noninteractive

apt-get update
apt-get -y upgrade

echo debconf shared/accepted-oracle-license-v1-1 select true | debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | debconf-set-selections
echo "oracle-java8-installer shared/accepted-oracle-license-v1-1 select true" | debconf-set-selections

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository ppa:webupd8team/java
apt-get update
apt-get -y upgrade
apt-get install -y --no-install-recommends oracle-java8-installer

apt-get install paxctl

paxctl -Cm /usr/lib/jvm/java*/bin/java
paxctl -Cm /usr/lib/jvm/java*/jre/bin/java
paxctl -Cm /usr/lib/jvm/java*/bin/keytool
paxctl -Cm /usr/lib/jvm/java*/jre/bin/keytool


rm -rf /var/lib/apt/lists/*
